name: Update README with Latest Stats

on:
  schedule:
    # Runs every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Generate README stats
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          HACKERRANK_USERNAME: ${{ secrets.HACKERRANK_USERNAME }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python scripts/update_readme.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated README with latest stats"
            git push
          fi